id: IED7E8174
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T23:50:36.571402'
last_modified: '2022-06-18T23:50:36.571415'
parser: null
source_metadata:
  title: Brief History of rNgog lo tsa ba Blo ldan shes rabs Tradition
  author: གསེར་མདོག་པཎ་ཆེན་ཤཱཀྱ་མཆོག་ལྡན།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2016-08-04);
    unrevised, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Pascale Hugon (Institute for the Cultural and Intellectual History
    of Asia, Vienna) (ph)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Pascale Hugon (ph)
  - Revisions/Corrections:Pascale Hugon (ph)
  text_witnesses: https://sakyaresearch.org/sources/1490
  bases:
    e0fc:
      title: Brief History of rNgog lo tsa ba Blo ldan shes rabs Tradition
      order: 1
      base_file: e0fc.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
